---
title: "TOR330"
description: "Post description"
author: "Päällysaho, Juha"
date: "2025-01-09"
data-modified: "2025-01-09"
draft: true
---

# Aloitus

Kuulin TOR-kisasta SwissPeaksin jälkimainingeissa (syyskuu 2023), oma kisa oli onnistunut (pääsin maaliin) ja seuraavalla viikolla alkanut kisa alppien toisella puolella hämmensi sillä hyvä että pääsin itse maaliin 170km koitoksessa. Muistelen että kisassa oli joukko suomalaisia (mm. Heikki H ja Karim L), Heikin olin tavannut vuonna 2017 eräässä kaljanjuonti orientoituneessa ulkoilutapahtumassa ja Karimin koronavuonna 2021 Ylläs-Pallas Special Editionissa (ensimmäinen 100-mailin kisani). Myöhemmin tapasin Karimin uudestaan Kullamannen tapahtumassa ruotsissa ja kehui suuresti Swisspeaksia, jossa nyt siis olin, läpeensä hämmentyneennä siitä miten alppikisa voi olla näinkin hidas ja raskas.

Suomalaisten suorituksista TORista en sen enempää miettinyt, sillä omassa kisakalenterissa oli vielä Kullamannenin 20km matka (jonka myöhemmin päivityin 55km:ään). Oma kiinnostus tapahtumaan heräsi joulukuussa Suomen Kuusamossa, pallottelin asiaa tyttöystäväni kanssa ja myös sitä että tapahtumaan on helpompi päästä Tanskan kiintiön kautta, jossa siis asumme tällä hetkellä. Lisäksi oma polkujuoksuputki on siinä mielessä onnistunut että olen päässyt kaikki tapahtumat aina maaliin, välillä rimaa hipoen ja osallistuminen TORiin varmasti jatkaisi tätä rimatyyliä, kyseessä olisi vasta toinen alppikisani. Tästä huolimatta olen tehnyt varmasti järjestmällisesti muistiinpanoa kisoistani viimeisen parin vuoden aikana ja tämä auttaa hahmottamaan mihin harjoittelussa tulisi keskittyä. Varsinkin asuminen Tanskassa tuo tähän lisähaasteen, mutta olin jotenkin onnistunut pääsemään SwissPeaksin läpi ja TOR olisi vain tuplamatka tähän verrattuna. Tästä tiivistin harjoittelun pääidean: Keskity vahvistamaan heikointa lenkkiä, joka on omassa tapauksessa lihaskestävyys.

# Alkuvuosi

Ennakko-odotusten mukaan ilmoittautuminen meni kuin olin suuniteltu, Tanskasta tuli osallistujia noin kahdeksan henkilöä, joista kuusi osallistui lopulta TORiin, minä mukaanlukien. 

Oma kokemukseni harjoittelusta on että jos aloittaa järjestelmällisen harjoittelun liian aikaisin (tammi/helmikuusssa), ennen kesää väsyy puhki (syy on mahdollisesti liian samantyyppiset harjoitukset). Tälle vuodelle tein siten että ulkoilin ja kävin satunnnaisesti puntilla helmikuun loppuun asti. Vietin maalis/huhtikuun ylläksellä pääosin hiihtäen, mutta pitäen yllä jonkinlaista juoksuiskutusta, ajatus oli keskittyä juoksuun toukokuusta eteenpäin ja välttää näin puhki väsyminen. 

# Kesä
Kesäharjoittelun aloitin Kööpenhaminan maratonilla, johon minulla oli aikaa valmistautua pari viikkoa.

# Kisa

## Osuus 1